# Generated by Django 3.2.4 on 2024-09-06 04:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20240905_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPointRedemptionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='Created At')),
                ('updated_at', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='Updated At')),
                ('used_point', models.BigIntegerField(default=0)),
                ('reference_name', models.CharField(choices=[('ORDER', 'Order')], max_length=50)),
                ('reference_id', models.CharField(max_length=255)),
                ('customer_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_point_redemption', to='user.customerpoint', verbose_name='Customer Point')),
            ],
            options={
                'verbose_name': 'Customer Point Redemption',
                'verbose_name_plural': 'Customer Point Redemptions',
            },
        ),
    ]
